project.name=AssignmentTracker
main.class=Main

src.dir=src
test.src=test
tool.dir=tools
build.dir=build
class.dir=${build.dir}/classes
test.class.dir=${build.dir}/test-classes
dist.dir=dist
doc.dir=build/docs/api
results.dir=results

tool.jars=${tool.dir}/jars
junit.jar=${tool.jars}/junit-platform-console-standalone-6.1.0-M1.jar
junit.results.dir=${results.dir}/junit

pmd.home=${tool.dir}/pmd
checkstyle.dir=${tool.dir}/checkstyle
checkstyle.suppressions.file=suppressions.xml
checkstyle.importcontrol.file=import-control.xml
translation.severity=warning

spotbugs.home=${tool.dir}/spotbugs

jacoco.results.dir=${results.dir}/jacoco
jacoco.exec.file=${results.dir}/jacoco/jacoco.exec

flatlaf.jar=lib/flatlaf-3.5.4.jar
flatlaf.themes.jar=lib/flatlaf-intellij-themes-3.5.4.jar
